openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v01/api/query/:
    get:
      operationId: listQueries
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    post:
      operationId: createQuery
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/v01/api/query/{id}/:
    get:
      operationId: retrieveQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    put:
      operationId: updateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyQuery
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this query.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v01/api/treatment/:
    get:
      operationId: listTreatments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
    post:
      operationId: createTreatment
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Treatment'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
  /api/v01/api/treatment/{id}/:
    get:
      operationId: retrieveTreatment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this treatment.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
    put:
      operationId: updateTreatment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this treatment.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Treatment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTreatment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this treatment.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Treatment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTreatment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this treatment.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v01/api/query/process_chat/:
    post:
      operationId: processChatQuery
      description: Process a chat query and generate a response.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
          description: ''
      tags:
      - api
  /api/v01/api/treatment/{id}/change_status/:
    put:
      operationId: changeStatusTreatment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this treatment.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Treatment'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treatment'
          description: ''
      tags:
      - api
components:
  schemas:
    Query:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        query_text:
          type: string
        response_text:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - query_text
      - response_text
    Treatment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        patient_name:
          type: string
          maxLength: 200
        date_of_illness:
          type: string
          format: date
        symptoms:
          type: string
        disease:
          type: string
          maxLength: 200
        diagnosis:
          type: string
        medication:
          type: string
        frequency:
          type: string
          maxLength: 100
        length_of_treatment:
          type: string
          maxLength: 100
        status:
          type: string
          maxLength: 100
      required:
      - patient_name
      - date_of_illness
      - symptoms
      - disease
      - diagnosis
      - medication
      - frequency
      - length_of_treatment
