# Generated by Django 5.1.2 on 2024-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
